const tags = [
  'astrophysics',
  'astronomy',
  'big bang',
  'black holes',
  'cosmic microwave background',
  'CERN',
  'dark energy',
  'dark matter',
  'dark fluid',
  'elementary particles',
  'Elon Mask',
  'gravity',
  'gravitational waves',
  'general relativity',
  'Higgs boson',
  'International Space Station',
  'large hadron collider',
  'JWST',
  'LHC',
  'LIGO',
  '"Milky Way galaxy"',
  'Multiverse',
  'NASA',
  'quantum physics',
  'quarks',
  'supermassive black hole',
  'space-time',
  'string theory',
  'SpaceX',
  'theoretical physics',
  'VIRGO',
];

export default tags;
