const tags = [
  'astronomy',
  'astrophysics',
  'big bang',
  'black holes',
  'cosmic microwave background',
  'CERN',
  'dark energy',
  'dark matter',
  'dark fluid',
  'elementary particles',
  'Elon Mask',
  'gravity',
  'gravitational waves',
  'higgs boson',
  'International Space Station',
  'large hadron collider',
  'LHC',
  'LIGO',
  '"Milky Way"',
  'multiverse',
  'NASA',
  'quantum physics',
  'quarks',
  'supermassive black hole',
  'space-time',
  'string theory',
  'SpaceX',
  'theoretical physics',
  'VIRGO',
];

export default tags;
