const tags = [
  'cosmic microwave background',
  'astronomy',
  'big bang',
  'black holes',
  'supermassive black hole',
  'quantum physics',
  'theoretical physics',
  'astrophysics',
  'space-time',
  'gravity',
  'gravitational waves',
  'multiverse',
  'NASA',
  'string theory',
  'dark energy',
  'dark matter',
  'dark fluid',
  'elementary particles',
  'CERN',
  'LHC',
  'large hadron collider',
  'higgs boson',
  'LIGO',
  'VIRGO',
  '"Milky Way"',
  'quarks',
  'International Space Station',
  'Elon Mask',
];

export default tags;
